# -*- coding: utf-8 -*-
"""reverse engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WKsRfQKKSeYrUs1bgvXrWb9RBSdaPNj
"""

from llama_index.llms import HuggingFaceLLM
from llama_index.prompts import PromptTemplate

# Define the prompt template
prompt_template = "https://www.acls.org/fellows-grantees/?_fellow_year=2023&_paged=1"
#Given the ACLS website URL: https://www.acls.org/fellows-grantees/?_fellow_year=2023&_paged=1, write a Python web scraper using BeautifulSoup to extract the grant information. Your scraper should:
#"""

# Define the LLM model and tokenizer
llm = HuggingFaceLLM(model_name="HuggingFaceH4/zephyr-7b-alpha", tokenizer_name="HuggingFaceH4/zephyr-7b-alpha")

# Define the prompt template
prompt_template = PromptTemplate(prompt_template)

# Generate the web scraping code using llm.complete
generated_code = llm.complete(prompt_template, max_tokens=500)

# Print the generated code
print(generated_code)